input {
    repeat_rate = 50
    repeat_delay = 300
    kb_layout = gb ,no 
#   kb_layout = no # for laptop
    kb_options = grp:alt_shift_toggle # swaps from gb to no with alt shift
#   kb_options = caps:swapescape # swap caps and esc 

    follow_mouse = 1

    sensitivity = 0.10 # 0.33 desktop 0.32 laptop (lenovo) 
    accel_profile = flat

    touchpad {
        natural_scroll = true
        scroll_factor = 0.3 
    }
}


# touchpad gestures
gestures {
}

