# windowrules
    windowrule = float on, match:class ^(Mullvad vpn)$, match:title ^(Mullvad vpn)$
    windowrule = suppress_event maximize, match:class .*
    windowrule = no_focus on, match:class ^$, match:title ^$, match:xwayland 1, match:float 1, match:fullscreen 0, match:pin 0
    windowrule = match:class ^(spotify)$, workspace special:music
    windowrule = float on , match:class ^(steam)$,  match:title negative:^(?!Steam$)
    windowrule = float on , match:title ^(Picture-in-Picture)

#layerrules

    layerrule = blur on, ignore_alpha 0.5, match:namespace waybar
    layerrule = blur on, ignore_alpha 0.5, match:namespace wlogout
    layerrule = blur on, match:namespace gtk-layer-shell
    layerrule = blur on, match:namespace logout_dialog # wlogout
    layerrule = blur on, ignore_alpha 0.5, match:namespace kitty
    layerrule = blur on, match:namespace ^(gtk-layer-shell)$
    layerrule = ignore_alpha 0.1, match:namespace ^(gtk-layer-shell)$, 
    layerrule = blur on, match:namespace ^(quickshell)$
    layerrule = ignore_alpha 0.1, match:namespace ^(quickshell)$, 



