exec-once = udiskie -t -a # -t = tray icon -a automount 
# exec-once = hypridle # laptops mostly atleast for now
exec-once = hyprsunset & qs & hyprpaper
exec-once = walker --gapplication-service

exec-once = [workspace 1 silent] $terminal
exec-once = [workspace special:music silent] spotify
exec-once = [workspace 2] $browser 


