env = XCURSOR_SIZE,24
env = HYPRCURSOR_SIZE,24
env = HYPRCURSOR_THEME,rose-pine-hyprcursor
env = ELECTRON_OZONE_PLATFORM_HINT,auto # auto wayland fallback to x11
env = GDK_BACKEND,wayland,x11

$terminal = kitty
$fileManager = dolphin
$menu = wofi --show drun
$browser = zen-browser


source = ~/.config/hypr/hyprland_configs/monitors.conf
source = ~/.config/hypr/hyprland_configs/input.conf

source = ~/.config/hypr/hyprland_configs/execute.conf
source = ~/.config/hypr/hyprland_configs/general.conf
source = ~/.config/hypr/hyprland_configs/binds.conf
source = ~/.config/hypr/hyprland_configs/rules.conf






